-- Initial database setup for SG Interactive Gallery
-- Creates tables and loads seed data

CREATE TABLE IF NOT EXISTS content (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(10) CHECK (type IN ('image', 'video')) NOT NULL,
  url VARCHAR(500) NOT NULL,
  category VARCHAR(50) CHECK (category IN ('Nature', 'Technology', 'Art')) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
  id SERIAL PRIMARY KEY,
  "contentId" INTEGER NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

INSERT INTO content (title, type, url, category) VALUES
  ('Bosque Verde', 'image', 'https://picsum.photos/seed/naturaleza1/800/600', 'Nature'),
  ('Montaña Nevada', 'image', 'https://picsum.photos/seed/naturaleza2/800/600', 'Nature'),
  ('Naturaleza en Movimiento', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Inteligencia Artificial', 'image', 'https://picsum.photos/seed/tech1/800/600', 'Technology'),
  ('Circuitos del Futuro', 'image', 'https://picsum.photos/seed/tech2/800/600', 'Technology'),
  ('Código en Acción', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Pintura Abstracta', 'image', 'https://picsum.photos/seed/arte1/800/600', 'Art'),
  ('Escultura Moderna', 'image', 'https://picsum.photos/seed/arte2/800/600', 'Art'),
  ('Arte en Movimiento', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Río Cristalino', 'image', 'https://picsum.photos/seed/nature10/800/600', 'Nature'),
  ('Cascada Tropical', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Amanecer en el Valle', 'image', 'https://picsum.photos/seed/nature12/800/600', 'Nature'),
  ('Lago Espejo', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Desierto Infinito', 'image', 'https://picsum.photos/seed/nature14/800/600', 'Nature'),
  ('Flores Silvestres', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Tormenta en el Mar', 'image', 'https://picsum.photos/seed/nature16/800/600', 'Nature'),
  ('Cañón Profundo', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Selva Amazónica', 'image', 'https://picsum.photos/seed/nature18/800/600', 'Nature'),
  ('Aurora Boreal', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Glaciar Azul', 'image', 'https://picsum.photos/seed/nature20/800/600', 'Nature'),
  ('Pradera Dorada', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Volcán Activo', 'image', 'https://picsum.photos/seed/nature22/800/600', 'Nature'),
  ('Playa Paradisíaca', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Bosque de Bambú', 'image', 'https://picsum.photos/seed/nature24/800/600', 'Nature'),
  ('Niebla Matutina', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Arrecife de Coral', 'image', 'https://picsum.photos/seed/nature26/800/600', 'Nature'),
  ('Montaña al Atardecer', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Campo de Lavanda', 'image', 'https://picsum.photos/seed/nature28/800/600', 'Nature'),
  ('Cueva Submarina', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Puesta de Sol Marina', 'image', 'https://picsum.photos/seed/nature30/800/600', 'Nature'),
  ('Bosque Otoñal', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Tundra Ártica', 'image', 'https://picsum.photos/seed/nature32/800/600', 'Nature'),
  ('Pantano Misterioso', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Colinas Verdes', 'image', 'https://picsum.photos/seed/nature34/800/600', 'Nature'),
  ('Río en la Selva', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Nieve Cayendo', 'image', 'https://picsum.photos/seed/nature35/800/600', 'Nature'),
  ('Olas del Océano', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Cielo Estrellado', 'image', 'https://picsum.photos/seed/nature36/800/600', 'Nature'),
  ('Amanecer Timelapse', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Acantilado Costero', 'image', 'https://picsum.photos/seed/nature37/800/600', 'Nature'),
  ('Tormenta Eléctrica', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Manantial Natural', 'image', 'https://picsum.photos/seed/nature38/800/600', 'Nature'),
  ('Cascada en 4K', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Bosque de Pinos', 'image', 'https://picsum.photos/seed/nature39/800/600', 'Nature'),
  ('Valle Brumoso', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Duna de Arena', 'image', 'https://picsum.photos/seed/nature41/800/600', 'Nature'),
  ('Lago Montañoso', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Palmeras Tropicales', 'image', 'https://picsum.photos/seed/nature43/800/600', 'Nature'),
  ('Rocas en el Mar', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Campo de Trigo', 'image', 'https://picsum.photos/seed/nature45/800/600', 'Nature'),
  ('Cueva de Hielo', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Prado Alpino', 'image', 'https://picsum.photos/seed/nature47/800/600', 'Nature'),
  ('Bahía Tranquila', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Árbol Centenario', 'image', 'https://picsum.photos/seed/nature49/800/600', 'Nature'),
  ('Llanura Africana', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Fiordo Noruego', 'image', 'https://picsum.photos/seed/nature51/800/600', 'Nature'),
  ('Selva Nublada', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Playa de Guijarros', 'image', 'https://picsum.photos/seed/nature53/800/600', 'Nature'),
  ('Río Congelado', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Montaña Volcánica', 'image', 'https://picsum.photos/seed/nature55/800/600', 'Nature'),
  ('Arco Natural', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Estanque de Lirios', 'image', 'https://picsum.photos/seed/nature57/800/600', 'Nature'),
  ('Costa Rocosa', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Geiser en Erupción', 'image', 'https://picsum.photos/seed/nature60/800/600', 'Nature'),
  ('Manglar Tropical', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Sendero en el Bosque', 'image', 'https://picsum.photos/seed/nature62/800/600', 'Nature'),
  ('Glaciar Patagónico', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Sabana al Atardecer', 'image', 'https://picsum.photos/seed/nature64/800/600', 'Nature'),
  ('Catarata Doble', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
  ('Meseta Árida', 'image', 'https://picsum.photos/seed/nature66/800/600', 'Nature'),
  ('Isla Volcánica', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Nature'),
  ('Bosque Encantado', 'image', 'https://picsum.photos/seed/nature68/800/600', 'Nature'),
  ('Mar de Nubes', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Nature'),
 
  -- TECHNOLOGY (64 records: 32 images, 32 videos)
  ('Robot Industrial', 'image', 'https://picsum.photos/seed/tech10/800/600', 'Technology'),
  ('Servidor en la Nube', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Chip Cuántico', 'image', 'https://picsum.photos/seed/tech12/800/600', 'Technology'),
  ('Pantalla Holográfica', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Dron de Última Generación', 'image', 'https://picsum.photos/seed/tech14/800/600', 'Technology'),
  ('Coche Autónomo', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Laboratorio Digital', 'image', 'https://picsum.photos/seed/tech16/800/600', 'Technology'),
  ('Red Neuronal Visual', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Ciudad Inteligente', 'image', 'https://picsum.photos/seed/tech18/800/600', 'Technology'),
  ('Impresora 3D', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Realidad Virtual', 'image', 'https://picsum.photos/seed/tech20/800/600', 'Technology'),
  ('Satélite Orbital', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Brazo Robótico', 'image', 'https://picsum.photos/seed/tech22/800/600', 'Technology'),
  ('Fibra Óptica', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Centro de Datos', 'image', 'https://picsum.photos/seed/tech24/800/600', 'Technology'),
  ('Nanotecnología', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Energía Solar', 'image', 'https://picsum.photos/seed/tech26/800/600', 'Technology'),
  ('Ciberespacio', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Pantalla Flexible', 'image', 'https://picsum.photos/seed/tech28/800/600', 'Technology'),
  ('Cohete Espacial', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('IA Generativa', 'image', 'https://picsum.photos/seed/tech30/800/600', 'Technology'),
  ('Robot en Acción', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Lanzamiento Espacial', 'image', 'https://picsum.photos/seed/tech32/800/600', 'Technology'),
  ('Demo de Realidad Aumentada', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Microchip Avanzado', 'image', 'https://picsum.photos/seed/tech34/800/600', 'Technology'),
  ('Torre de Telecomunicaciones', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Supercomputadora', 'image', 'https://picsum.photos/seed/tech36/800/600', 'Technology'),
  ('Red 5G', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Exoesqueleto Robótico', 'image', 'https://picsum.photos/seed/tech38/800/600', 'Technology'),
  ('Energía de Fusión', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Submarino Autónomo', 'image', 'https://picsum.photos/seed/tech40/800/600', 'Technology'),
  ('Telescopio Espacial', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Interfaz Cerebral', 'image', 'https://picsum.photos/seed/tech42/800/600', 'Technology'),
  ('Vehículo Eléctrico', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Computación Cuántica', 'image', 'https://picsum.photos/seed/tech44/800/600', 'Technology'),
  ('Sensor Biométrico', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Planta Solar', 'image', 'https://picsum.photos/seed/tech46/800/600', 'Technology'),
  ('Arquitectura Digital', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Turbina Eólica', 'image', 'https://picsum.photos/seed/tech48/800/600', 'Technology'),
  ('Estación Espacial', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Algoritmo Visual', 'image', 'https://picsum.photos/seed/tech50/800/600', 'Technology'),
  ('Laboratorio Biotec', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Pantalla 8K', 'image', 'https://picsum.photos/seed/tech52/800/600', 'Technology'),
  ('Batería del Futuro', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Cámara Cuántica', 'image', 'https://picsum.photos/seed/tech54/800/600', 'Technology'),
  ('Sistema de Navegación', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Procesador Avanzado', 'image', 'https://picsum.photos/seed/tech56/800/600', 'Technology'),
  ('Prototipo Futurista', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Simulación Molecular', 'image', 'https://picsum.photos/seed/tech58/800/600', 'Technology'),
  ('Red de Sensores', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Fábrica Automatizada', 'image', 'https://picsum.photos/seed/tech60/800/600', 'Technology'),
  ('Escáner Médico', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Cohete Reutilizable', 'image', 'https://picsum.photos/seed/tech62/800/600', 'Technology'),
  ('Drone de Entrega', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Laboratorio de IA', 'image', 'https://picsum.photos/seed/tech64/800/600', 'Technology'),
  ('Ciudad del Futuro', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Módulo Lunar', 'image', 'https://picsum.photos/seed/tech66/800/600', 'Technology'),
  ('Nanobot Médico', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Pantalla Transparente', 'image', 'https://picsum.photos/seed/tech68/800/600', 'Technology'),
  ('Motor Iónico', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
  ('Simulador de Vuelo', 'image', 'https://picsum.photos/seed/tech70/800/600', 'Technology'),
  ('Chip de Memoria', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Technology'),
  ('Rover Marciano', 'image', 'https://picsum.photos/seed/tech72/800/600', 'Technology'),
  ('Futuro de la IA', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Technology'),
 
  -- ART (63 records: 32 images, 31 videos)
  ('Mural Urbano', 'image', 'https://picsum.photos/seed/art10/800/600', 'Art'),
  ('Performance Visual', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Fotografía Conceptual', 'image', 'https://picsum.photos/seed/art12/800/600', 'Art'),
  ('Arte en Movimiento', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Instalación Luminosa', 'image', 'https://picsum.photos/seed/art14/800/600', 'Art'),
  ('Instalación Interactiva', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Collage Contemporáneo', 'image', 'https://picsum.photos/seed/art16/800/600', 'Art'),
  ('Danza Contemporánea', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Graffiti Digital', 'image', 'https://picsum.photos/seed/art18/800/600', 'Art'),
  ('Videoarte Experimental', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Escultura de Luz', 'image', 'https://picsum.photos/seed/art20/800/600', 'Art'),
  ('Arte Cinético en Video', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Acuarela Abstracta', 'image', 'https://picsum.photos/seed/art22/800/600', 'Art'),
  ('Escultura en Movimiento', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Arte Generativo', 'image', 'https://picsum.photos/seed/art24/800/600', 'Art'),
  ('Mural en Proceso', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Retrato Expresionista', 'image', 'https://picsum.photos/seed/art26/800/600', 'Art'),
  ('Instalación de Luz', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Mosaico Digital', 'image', 'https://picsum.photos/seed/art28/800/600', 'Art'),
  ('Performance Callejero', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Escultura Metálica', 'image', 'https://picsum.photos/seed/art30/800/600', 'Art'),
  ('Arte Experimental', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Ilustración Surrealista', 'image', 'https://picsum.photos/seed/art32/800/600', 'Art'),
  ('Obra Interactiva', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Obra Minimalista', 'image', 'https://picsum.photos/seed/art34/800/600', 'Art'),
  ('Animación Artística', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Arte Callejero', 'image', 'https://picsum.photos/seed/art36/800/600', 'Art'),
  ('Proyección Artística', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Pintura al Óleo', 'image', 'https://picsum.photos/seed/art38/800/600', 'Art'),
  ('Arte Digital Animado', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Escultura de Vidrio', 'image', 'https://picsum.photos/seed/art40/800/600', 'Art'),
  ('Cortometraje Visual', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Fotografía Urbana', 'image', 'https://picsum.photos/seed/art42/800/600', 'Art'),
  ('Loop Visual', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Arte Óptico', 'image', 'https://picsum.photos/seed/art44/800/600', 'Art'),
  ('Secuencia Abstracta', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Dibujo Hiperrealista', 'image', 'https://picsum.photos/seed/art46/800/600', 'Art'),
  ('Arte en Neón', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Cerámica Artesanal', 'image', 'https://picsum.photos/seed/art48/800/600', 'Art'),
  ('Pintura Gestual en Video', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Tapiz Moderno', 'image', 'https://picsum.photos/seed/art50/800/600', 'Art'),
  ('Arte Fractal Animado', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Arte en Papel', 'image', 'https://picsum.photos/seed/art52/800/600', 'Art'),
  ('Escultura Cinética', 'video', 'https://www.w3schools.com/html/movie.mp4', 'Art'),
  ('Xilografía Contemporánea', 'image', 'https://picsum.photos/seed/art54/800/600', 'Art'),
  ('Timelapse Artístico', 'video', 'https://www.w3schools.com/html/mov_bbb.mp4', 'Art'),
  ('Fotografía Analógica', 'image', 'https://picsum.photos/seed/art56/800/600', 'Art'),
  ('Obra Pop Art', 'image', 'https://picsum.photos/seed/art58/800/600', 'Art'),
  ('Pintura Impresionista', 'image', 'https://picsum.photos/seed/art60/800/600', 'Art'),
  ('Arte en Madera', 'image', 'https://picsum.photos/seed/art62/800/600', 'Art'),
  ('Fotografía de Moda', 'image', 'https://picsum.photos/seed/art64/800/600', 'Art'),
  ('Escultura de Arena', 'image', 'https://picsum.photos/seed/art66/800/600', 'Art'),
  ('Arte Conceptual', 'image', 'https://picsum.photos/seed/art68/800/600', 'Art'),
  ('Pintura Acrílica', 'image', 'https://picsum.photos/seed/art70/800/600', 'Art'),
  ('Ilustración Digital', 'image', 'https://picsum.photos/seed/art72/800/600', 'Art'),
  ('Escultura en Bronce', 'image', 'https://picsum.photos/seed/art74/800/600', 'Art'),
  ('Arte Psicodélico', 'image', 'https://picsum.photos/seed/art76/800/600', 'Art'),
  ('Bordado Artístico', 'image', 'https://picsum.photos/seed/art78/800/600', 'Art'),
  ('Fotografía Nocturna', 'image', 'https://picsum.photos/seed/art80/800/600', 'Art'),
  ('Arte en Hierro', 'image', 'https://picsum.photos/seed/art82/800/600', 'Art'),
  ('Grabado Contemporáneo', 'image', 'https://picsum.photos/seed/art84/800/600', 'Art'),
  ('Diseño Tipográfico', 'image', 'https://picsum.photos/seed/art86/800/600', 'Art'),
  ('Obra Neoexpresionista', 'image', 'https://picsum.photos/seed/art88/800/600', 'Art');